# Generated by Django 2.1.7 on 2019-04-14 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('admin_email', models.EmailField(max_length=254)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('event', models.PositiveIntegerField(default=0)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.TextField()),
                ('active', models.BooleanField()),
                ('caregroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.CareGroup')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=40)),
                ('age', models.IntegerField()),
                ('caregroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.CareGroup')),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='sensors.Device')),
            ],
        ),
        migrations.AddField(
            model_name='data',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sensors.Device'),
        ),
        migrations.AddField(
            model_name='data',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sensors.Patient'),
        ),
    ]
