# Generated by Django 2.1.7 on 2019-03-18 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=40)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Greeting',
        ),
    ]
