# Generated by Django 2.1.7 on 2019-04-15 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='time',
            field=models.IntegerField(),
        ),
    ]
