# Generated by Django 2.1.7 on 2019-04-30 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_auto_20190430_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='caregroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sensors.CareGroup'),
        ),
    ]
