# Generated by Django 2.1.7 on 2019-03-26 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_auto_20190318_2006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
