# Generated by Django 2.1.7 on 2019-05-23 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_auto_20190523_0244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='patient',
        ),
    ]
