# Generated by Django 2.1.7 on 2019-05-23 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_remove_data_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sensors.Patient'),
        ),
    ]
