# Generated by Django 2.1.7 on 2019-03-27 19:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sensors', '0003_auto_20190326_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('admin_email', models.EmailField(max_length=254)),
                ('user_list', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
