# Generated by Django 2.2 on 2019-04-18 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_auto_20190416_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='time',
            field=models.IntegerField(),
        ),
    ]
