# Generated by Django 2.1.7 on 2019-04-30 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_auto_20190430_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('c', 'clean'), ('d', 'dirty')], default='c', max_length=20),
        ),
    ]
