# Generated by Django 2.1.7 on 2019-04-30 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0004_patient_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='last_event',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
