# Generated by Django 2.1.7 on 2019-07-07 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0005_auto_20190523_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='active',
            field=models.BooleanField(null=True),
        ),
    ]
