# Generated by Django 2.1.7 on 2019-04-30 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0005_patient_last_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='last_event',
            field=models.DateTimeField(null=True),
        ),
    ]
