# Generated by Django 2.1.7 on 2019-04-02 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0005_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='event',
            field=models.BooleanField(default=False),
        ),
    ]
