# Generated by Django 2.1.7 on 2019-04-02 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0006_data_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='event',
            field=models.IntegerField(default=0),
        ),
    ]
