# Generated by Django 2.1.7 on 2019-04-02 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0007_auto_20190402_0309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='patient',
        ),
        migrations.AddField(
            model_name='data',
            name='sensor_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='data',
            name='event',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
